MF-74  Config library should import default config file using import-map (#27)
* Work on configuration.

Tests throwing
    ReferenceError: System is not defined

* Get config skeleton working for logo.

Tests failing with
  Cannot find module '@openmrs/esm-config' from 'login.component.tsx'

* Some work

* More toward import-map config-file support

* None of that MF-74 stuff just yet; use esm-module-config from npm

* Get logo configuration working nice

* Start switching to use the config react hook

* WIP

* Move suspense out to root-decorator; tests failing

* PR review

* Making pre-commit hook faster